name: analytics_inspector
description: Analytics Inspector kit for flutter_ume.
version: 0.0.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/dmsrgv/flutter_ume

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65


